[package]
name = "tui-user-input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.0"
tui = "0.19.0"
unicode-width = "0.1.10"
